name: chat_repository
description: Dart packages for chat
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.11.0
  equatable: ^2.0.5
  firebase_auth: ^4.11.1
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.2
  path_provider: ^2.1.1
  uuid: null

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
