name: post_repository
description: Dart packages for post 
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  # Fire Base
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
